preferred_syntax = :scss
http_path = '/'
css_dir = 'css/'
sass_dir = 'resources/scss'
images_dir = 'resources/images'
javascripts_dir = 'js/'
relative_assets = true
line_comments = true
# output_style = :compressed